import { AirPort } from '.';

export const domesticAirports: Array<AirPort> = [
    {
        Id: 'HAN',
        Name: 'Sân Bay Quốc Tế Nội Bài',
        CityId: 'HAN',
        CityName: 'TP.Hà Nội',
        CountryId: 'VN',
        CountryName: 'Việt Nam',
        PlaceId: null,
        PlaceName: null,
        IsDomestic: true,
    },
    {
        Id: 'SGN',
        Name: 'Sân Bay Quốc Tế Tân Sơn Nhất',
        CityId: 'SGN',
        CityName: 'TP.Hồ Chí Minh',
        CountryId: 'VN',
        CountryName: 'Việt Nam',
        PlaceId: null,
        PlaceName: null,
        IsDomestic: true,
    },
    {
        Id: 'DAD',
        Name: 'Sân bay Đà Nẵng',
        CityId: 'DAD',
        CityName: 'Đà Nẵng',
        CountryId: 'VN',
        CountryName: 'Việt Nam',
        PlaceId: null,
        PlaceName: null,
        IsDomestic: true,
    },
    {
        Id: 'CXR',
        Name: 'Sân bay Cam Ranh',
        CityId: 'NHA',
        CityName: 'Nha Trang',
        CountryId: 'VN',
        CountryName: 'Việt Nam',
        PlaceId: null,
        PlaceName: null,
        IsDomestic: true,
    },
    {
        Id: 'DLI',
        Name: 'Sân bay Liên Khương',
        CityId: 'DLI',
        CityName: 'Đà Lạt',
        CountryId: 'VN',
        CountryName: 'Việt Nam',
        PlaceId: null,
        PlaceName: null,
        IsDomestic: true,
    },
    {
        Id: 'NHA',
        Name: 'Sân bay Cam Ranh',
        CityId: 'NHA',
        CityName: 'Nha Trang',
        CountryId: 'VN',
        CountryName: 'Việt Nam',
        PlaceId: null,
        PlaceName: null,
        IsDomestic: true,
    },
    {
        Id: 'PQC',
        Name: 'Sân bay Phú Quốc',
        CityId: 'PQC',
        CityName: 'Phú Quốc',
        CountryId: 'VN',
        CountryName: 'Việt Nam',
        PlaceId: null,
        PlaceName: null,
        IsDomestic: true,
    },
    {
        Id: 'HUI',
        Name: 'Sân bay Phú Bài',
        CityId: 'HUI',
        CityName: 'Huế',
        CountryId: 'VN',
        CountryName: 'Việt Nam',
        PlaceId: null,
        PlaceName: null,
        IsDomestic: true,
    },
    {
        Id: 'HPH',
        Name: 'Sân bay Cát Bi',
        CityId: 'HPH',
        CityName: 'Hải Phòng',
        CountryId: 'VN',
        CountryName: 'Việt Nam',
        PlaceId: null,
        PlaceName: null,
        IsDomestic: true,
    },
    {
        Id: 'VII',
        Name: 'Sân bay Vinh',
        CityId: 'VII',
        CityName: 'Vinh',
        CountryId: 'VN',
        CountryName: 'Việt Nam',
        PlaceId: null,
        PlaceName: null,
        IsDomestic: true,
    },
    {
        Id: 'VDO',
        Name: 'Sân bay quốc tế Vân Đồn',
        CityId: 'VDO',
        CityName: 'Quảng Ninh',
        CountryId: 'VN',
        CountryName: 'Việt Nam',
        PlaceId: null,
        PlaceName: null,
        IsDomestic: true,
    },
    {
        Id: 'THD',
        Name: 'Sân bay Thọ Xuân',
        CityId: 'THD',
        CityName: 'Thanh Hóa',
        CountryId: 'VN',
        CountryName: 'Việt Nam',
        PlaceId: null,
        PlaceName: null,
        IsDomestic: true,
    },
    {
        Id: 'DIN',
        Name: 'Sân bay Điện Biên',
        CityId: 'DIN',
        CityName: 'Điện Biên Phủ',
        CountryId: 'VN',
        CountryName: 'Viet nam',
        PlaceId: null,
        PlaceName: null,
        IsDomestic: true,
    },
    {
        Id: 'VDH',
        Name: 'Sân bay Đồng Hới',
        CityId: 'VDH',
        CityName: 'Quảng Bình',
        CountryId: 'VN',
        CountryName: 'Việt Nam',
        PlaceId: null,
        PlaceName: null,
        IsDomestic: true,
    },
    {
        Id: 'VCL',
        Name: 'Sân bay Chu Lai',
        CityId: 'VCL',
        CityName: 'Quảng Nam',
        CountryId: 'VN',
        CountryName: 'Việt Nam',
        PlaceId: null,
        PlaceName: null,
        IsDomestic: true,
    },
    {
        Id: 'PXU',
        Name: 'Sân bay Pleiku ',
        CityId: 'PXU',
        CityName: 'PleiKu',
        CountryId: 'VN',
        CountryName: 'Việt Nam',
        PlaceId: null,
        PlaceName: null,
        IsDomestic: true,
    },
    {
        Id: 'TBB',
        Name: 'Sân bay Tuy Hòa',
        CityId: 'TBB',
        CityName: 'Phú Yên',
        CountryId: 'VN',
        CountryName: 'Việt Nam',
        PlaceId: null,
        PlaceName: null,
        IsDomestic: true,
    },
    {
        Id: 'UIH',
        Name: 'Phù Cát',
        CityId: 'UIH',
        CityName: 'Qui Nhon',
        CountryId: 'VN',
        CountryName: 'Viet nam',
        PlaceId: null,
        PlaceName: null,
        IsDomestic: true,
    },
    {
        Id: 'BMV',
        Name: 'Sân bay Buôn Ma Thuột',
        CityId: 'BMV',
        CityName: 'Buôn Ma Thuột',
        CountryId: 'VN',
        CountryName: 'Việt Nam',
        PlaceId: null,
        PlaceName: null,
        IsDomestic: true,
    },
    {
        Id: 'CAH',
        Name: 'Sân bay Cà Mau',
        CityId: 'CAH',
        CityName: 'Ca Mau',
        CountryId: 'VN',
        CountryName: 'Việt Nam',
        PlaceId: null,
        PlaceName: null,
        IsDomestic: true,
    },
    {
        Id: 'VCA',
        Name: 'Sân bay Cần Thơ',
        CityId: 'VCA',
        CityName: 'Cần Thơ',
        CountryId: 'VN',
        CountryName: 'Việt Nam',
        PlaceId: null,
        PlaceName: null,
        IsDomestic: true,
    },
    {
        Id: 'VCS',
        Name: 'Sân bay Cỏ Ống',
        CityId: 'VCS',
        CityName: 'Côn Đảo',
        CountryId: 'VN',
        CountryName: 'Việt Nam',
        PlaceId: null,
        PlaceName: null,
        IsDomestic: true,
    },
    {
        Id: 'VKG',
        Name: 'Rach Gia',
        CityId: 'VKG',
        CityName: 'Rach Gia',
        CountryId: 'VN',
        CountryName: 'Viet nam',
        PlaceId: null,
        PlaceName: null,
        IsDomestic: true,
    },
];

// export const domesticAirports2: {
//     Northern: Array<AirPort>;
//     CentralRegion: Array<AirPort>;
//     Southern: Array<AirPort>;
// } = {
//     Northern: [
//         {
//             Id: 'HAN',
//             Name: 'Sân Bay Quốc Tế Nội Bài',
//             CityId: 'HAN',
//             CityName: 'TP.Hà Nội',
//             CountryId: 'VN',
//             CountryName: 'Việt Nam',
//             PlaceId: null,
//             PlaceName: null,
//             IsDomestic: true,
//         },
//         {
//             Id: 'HPH',
//             Name: 'Sân bay Cát Bi',
//             CityId: 'HPH',
//             CityName: 'Hải Phòng',
//             CountryId: 'VN',
//             CountryName: 'Việt Nam',
//             PlaceId: null,
//             PlaceName: null,
//             IsDomestic: true,
//         },
//         {
//             Id: 'VDO',
//             Name: 'Sân bay quốc tế Vân Đồn',
//             CityId: 'VDO',
//             CityName: 'Quảng Ninh',
//             CountryId: 'VN',
//             CountryName: 'Việt Nam',
//             PlaceId: null,
//             PlaceName: null,
//             IsDomestic: true,
//         },
//         {
//             Id: 'VII',
//             Name: 'Sân bay Vinh',
//             CityId: 'VII',
//             CityName: 'Vinh',
//             CountryId: 'VN',
//             CountryName: 'Việt Nam',
//             PlaceId: null,
//             PlaceName: null,
//             IsDomestic: true,
//         },
//         {
//             Id: 'THD',
//             Name: 'Sân bay Thọ Xuân',
//             CityId: 'THD',
//             CityName: 'Thanh Hóa',
//             CountryId: 'VN',
//             CountryName: 'Việt Nam',
//             PlaceId: null,
//             PlaceName: null,
//             IsDomestic: true,
//         },
//         {
//             Id: 'DIN',
//             Name: 'Sân bay Điện Biên',
//             CityId: 'DIN',
//             CityName: 'Điện Biên Phủ',
//             CountryId: 'VN',
//             CountryName: 'Viet nam',
//             PlaceId: null,
//             PlaceName: null,
//             IsDomestic: true,
//         },
//     ],
//     CentralRegion: [
//         {
//             Id: 'DAD',
//             Name: 'Sân bay Đà Nẵng',
//             CityId: 'DAD',
//             CityName: 'Đà Nẵng',
//             CountryId: 'VN',
//             CountryName: 'Việt Nam',
//             PlaceId: null,
//             PlaceName: null,
//             IsDomestic: true,
//         },
//         {
//             Id: 'VDH',
//             Name: 'Sân bay Đồng Hới',
//             CityId: 'VDH',
//             CityName: 'Quảng Bình',
//             CountryId: 'VN',
//             CountryName: 'Việt Nam',
//             PlaceId: null,
//             PlaceName: null,
//             IsDomestic: true,
//         },
//         {
//             Id: 'VCL',
//             Name: 'Sân bay Chu Lai',
//             CityId: 'VCL',
//             CityName: 'Quảng Nam',
//             CountryId: 'VN',
//             CountryName: 'Việt Nam',
//             PlaceId: null,
//             PlaceName: null,
//             IsDomestic: true,
//         },
//         {
//             Id: 'PXU',
//             Name: 'Sân bay Pleiku ',
//             CityId: 'PXU',
//             CityName: 'PleiKu',
//             CountryId: 'VN',
//             CountryName: 'Việt Nam',
//             PlaceId: null,
//             PlaceName: null,
//             IsDomestic: true,
//         },
//         {
//             Id: 'TBB',
//             Name: 'Sân bay Tuy Hòa',
//             CityId: 'TBB',
//             CityName: 'Phú Yên',
//             CountryId: 'VN',
//             CountryName: 'Việt Nam',
//             PlaceId: null,
//             PlaceName: null,
//             IsDomestic: true,
//         },
//         {
//             Id: 'HUI',
//             Name: 'Sân bay Phú Bài',
//             CityId: 'HUI',
//             CityName: 'Huế',
//             CountryId: 'VN',
//             CountryName: 'Việt Nam',
//             PlaceId: null,
//             PlaceName: null,
//             IsDomestic: true,
//         },
//         {
//             Id: 'NHA',
//             Name: 'Sân bay Cam Ranh',
//             CityId: 'NHA',
//             CityName: 'Nha Trang',
//             CountryId: 'VN',
//             CountryName: 'Việt Nam',
//             PlaceId: null,
//             PlaceName: null,
//             IsDomestic: true,
//         },
//         {
//             Id: 'UIH',
//             Name: 'Phù Cát',
//             CityId: 'UIH',
//             CityName: 'Qui Nhon',
//             CountryId: 'VN',
//             CountryName: 'Viet nam',
//             PlaceId: null,
//             PlaceName: null,
//             IsDomestic: true,
//         },
//         {
//             Id: 'DLI',
//             Name: 'Sân bay Liên Khương',
//             CityId: 'DLI',
//             CityName: 'Đà Lạt',
//             CountryId: 'VN',
//             CountryName: 'Việt Nam',
//             PlaceId: null,
//             PlaceName: null,
//             IsDomestic: true,
//         },
//     ],
//     Southern: [
//         {
//             Id: 'SGN',
//             Name: 'Sân Bay Quốc Tế Tân Sơn Nhất',
//             CityId: 'SGN',
//             CityName: 'TP.Hồ Chí Minh',
//             CountryId: 'VN',
//             CountryName: 'Việt Nam',
//             PlaceId: null,
//             PlaceName: null,
//             IsDomestic: true,
//         },
//         {
//             Id: 'BMV',
//             Name: 'Sân bay Buôn Ma Thuột',
//             CityId: 'BMV',
//             CityName: 'Buôn Ma Thuột',
//             CountryId: 'VN',
//             CountryName: 'Việt Nam',
//             PlaceId: null,
//             PlaceName: null,
//             IsDomestic: true,
//         },
//         {
//             Id: 'CAH',
//             Name: 'Sân bay Cà Mau',
//             CityId: 'CAH',
//             CityName: 'Ca Mau',
//             CountryId: 'VN',
//             CountryName: 'Việt Nam',
//             PlaceId: null,
//             PlaceName: null,
//             IsDomestic: true,
//         },
//         {
//             Id: 'CXR',
//             Name: 'Sân bay Cam Ranh',
//             CityId: 'NHA',
//             CityName: 'Nha Trang',
//             CountryId: 'VN',
//             CountryName: 'Việt Nam',
//             PlaceId: null,
//             PlaceName: null,
//             IsDomestic: true,
//         },
//         {
//             Id: 'PQC',
//             Name: 'Sân bay Phú Quốc',
//             CityId: 'PQC',
//             CityName: 'Phú Quốc',
//             CountryId: 'VN',
//             CountryName: 'Việt Nam',
//             PlaceId: null,
//             PlaceName: null,
//             IsDomestic: true,
//         },
//         {
//             Id: 'VCA',
//             Name: 'Sân bay Cần Thơ',
//             CityId: 'VCA',
//             CityName: 'Cần Thơ',
//             CountryId: 'VN',
//             CountryName: 'Việt Nam',
//             PlaceId: null,
//             PlaceName: null,
//             IsDomestic: true,
//         },
//         {
//             Id: 'VCS',
//             Name: 'Sân bay Cỏ Ống',
//             CityId: 'VCS',
//             CityName: 'Côn Đảo',
//             CountryId: 'VN',
//             CountryName: 'Việt Nam',
//             PlaceId: null,
//             PlaceName: null,
//             IsDomestic: true,
//         },
//         {
//             Id: 'VKG',
//             Name: 'Rach Gia',
//             CityId: 'VKG',
//             CityName: 'Rach Gia',
//             CountryId: 'VN',
//             CountryName: 'Viet nam',
//             PlaceId: null,
//             PlaceName: null,
//             IsDomestic: true,
//         },
//     ],
// };
